#!/bin/bash
rm $OPENSHIFT_PYTHON_LOG_DIR/python_log.log $OPENSHIFT_PYTHON_LOG_DIR/nohup_for_scheduler.out
touch $OPENSHIFT_PYTHON_LOG_DIR/python_log.log $OPENSHIFT_PYTHON_LOG_DIR/nohup_for_scheduler.out
phantom=$(ps -eaf | grep -v grep | grep phantomjs | grep -v $$)
if [ "$phantom" ]; then
echo "Phantomjs is already running";
else nohup ${OPENSHIFT_DATA_DIR}/phantomjs/bin/phantomjs --webdriver=$OPENSHIFT_PYTHON_IP:15005 &
 fi
 sleep 10
scheduler_pid=$(ps -eaf | grep -v grep | grep run_scheduler.py | grep -v $$ | awk '{ print $2 }')
if [ "$scheduler_pid" ]; then
kill -SIGKILL $scheduler_pid
echo Scheduler with PID: $scheduler_pid was killed
 fi
chmod +x $OPENSHIFT_REPO_DIR/run_scheduler.py
nohup python $OPENSHIFT_REPO_DIR/run_scheduler.py > /dev/null 2>&1&
echo "Scheduler started successfully"
